# Generated by Django 5.0.1 on 2024-01-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0004_alter_question_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
