# Generated by Django 5.0.1 on 2024-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0005_remove_question_date_created_remove_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
