# Generated by Django 5.0.1 on 2024-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0006_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
