# Generated by Django 5.0.1 on 2024-01-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0009_question_likes_alter_question_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
    ]
