# Generated by Django 5.0.1 on 2024-01-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0010_remove_question_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_created',
        ),
    ]
