# Generated by Django 5.0.1 on 2024-01-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0011_remove_comment_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
