# Generated by Django 5.0.1 on 2024-01-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackbase', '0012_remove_question_content_remove_question_likes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
